{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "startracker.fullname" . }}-api
  labels:
    {{- include "startracker.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ include "startracker.apiSecretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.api.secret.key }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key | quote }}
        {{- if .Values.externalSecrets.remoteRef.property }}
        property: {{ .Values.externalSecrets.remoteRef.property | quote }}
        {{- end }}
{{- end }}
