apiVersion: v1
kind: Service
metadata:
  name: {{ include "startracker.fullname" . }}-ui
  labels:
    {{- include "startracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.service.targetPort }}
      protocol: TCP
